/** @format */

module.exports = [
	{
		item_name: 'Business savings deposit',
		amount: 1200,
		date: '2022-07-15',
		from: 'Michael Kleemoff',
		category: 'Business Savings',
		description:
			'Deposit to Lil Beans Bakery and Cafe business savings account.',
		type: 'credit',
	},
	{
		item_name: 'Personal savings deposit',
		amount: 200,
		date: '2022-07-08',
		from: 'Michael Kleemoff',
		category: 'Personal Savings',
		description: 'Deposit to personal savings account.',
		type: 'credit',
	},
	{
		item_name: 'Income',
		amount: 650,
		date: '2022-07-22',
		from: 'Lil Beans Bakery and Cafe',
		category: 'Income',
		description:
			'Deposit to personal checking account from Lil Beans Bakery and Cafe.',
		type: 'credit',
	},
	{
		item_name: 'Mitsubishi Mirage payment',
		amount: -287,
		date: '2022-07-05',
		from: 'Mitsubishi Auto Financing',
		category: 'Car Finance',
		description: 'Monthly car payment to Mitsubishi Auto Financing.',
		type: 'debit',
	},
	{
		item_name: 'Car insurance',
		amount: -190,
		date: '2022-07-15',
		from: 'Dairyland Auto Insurance',
		category: 'Car Insurance',
		description: 'Monthly car insurance payment to Dairyland Auto Insurance.',
		type: 'debit',
	},
	{
		item_name: 'Electricity',
		amount: -250,
		date: '2022-07-05',
		from: 'Con Edison',
		category: 'Electricity',
		description: 'Monthly electricity bill payment to Con Edison.',
		type: 'debit',
	},
	{
		item_name: 'Internet/cable',
		amount: -300,
		date: '2022-07-01',
		from: 'Spectrum',
		category: 'Internet/Cable',
		description: 'Monthly cable/internet bill payment to Spectrum.',
		type: 'debit',
	},
	{
		item_name: 'Groceries',
		amount: -220,
		date: '2022-07-23',
		from: 'Wegmans Food Markets',
		category: 'Groceries',
		description: 'Shopping at Wegmans Food Markets for weekly groceries.',
		type: 'debit',
	},
	{
		item_name: 'Gasoline',
		amount: -100,
		date: '2022-07-21',
		from: 'Exxon',
		category: 'Gasoline',
		description: 'Fill the car with gasoline at Exxon gas station.',
		type: 'debit',
	},
];
